apiVersion: v1
kind: Service
metadata:
  name: csgames-mail-staging-backend
spec:
  selector:
    app: csgames-mail-staging
  ports:
  - name: csgames-mail-staging-backend
    targetPort: 8090
    port: 8090
  type: NodePort