version: '3'
services:
  # gateway:
  #   build: gateway/
  #   volumes:
  #     - ./gateway/app:/config
  #   ports:
  #     - "8000:8000"
  #   env_file: gateway/.env
  #   networks:
  #     - app
  sts:
    build: sts/
    volumes:
      - ./sts/keys:/keys
    ports:
      - "5555:5555"
    env_file: sts/.env
    networks:
      - app
  mail:
    build: mail/
    volumes:
      - ./sts/keys:/keys
    ports:
      - "8090:8090"
    env_file: mail/.env
    networks:
      - app
networks:
  app:
    driver: bridge