version: '3'
services:
  gateway:
    build: gateway/
    volumes:
      - ./gateway/app/proxy-config.json:/config/proxy-config.json
    network_mode: host
    env_file: gateway/.env
  sts:
    build: sts/
    volumes:
      - ./sts/keys:/keys
    network_mode: host
    env_file: sts/.env
  mail:
    build: mail/
    volumes:
      - ./sts/keys/public.pem:/keys/public.pem
    network_mode: host
    env_file: mail/.env