apiVersion: v1
kind: Service
metadata:
  name: csgames-api-prod-backend
  labels:
    app: csgames-api-prod
    role: master
    tier: backend
spec:
  ports:
  - name: csgames-api-prod-backend
    targetPort: 8080
    port: 8080
  - name: csgames-api-ws-prod-backend
    targetPort: 8081
    port: 8081
  selector:
    app: csgames-api-prod
    role: master
    tier: backend