apiVersion: v1
kind: Service
metadata:
  name: csgames-api-prod-backend
  labels:
    app: csgames-api-prod
    role: master
    tier: backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: csgames-api-prod
    role: master
    tier: backend