apiVersion: apps/v1
kind: Deployment
metadata:
  name: csgames-mail-prod-master
  labels:
    app: csgames-mail-prod
spec:
  selector:
    matchLabels:
      app: csgames-mail-prod
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: csgames-mail-prod
        role: master
        tier: backend
    spec:
      volumes:
      - name: sts-key
        secret:
          secretName: public-key-prod
      containers:
      - name: csgames-mail-prod
        image: "polyhx/mail:latest"
        resources:
          requests:
            cpu: "60m"
          limits:
            cpu: "70m"
        volumeMounts:
        - name: sts-key
          mountPath: /var/secret
        env:
        - name: DB_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: DB_ADDRESS
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: DB_PASSWORD
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: DB_USERNAME
        - name: JWT_PUBLIC_KEY
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: JWT_PUBLIC_KEY
        - name: MAILGUN_API_KEY
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: MAILGUN_API_KEY
        - name: MAILGUN_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: MAILGUN_DOMAIN
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: PORT
        - name: VERSION
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: VERSION