apiVersion: v1
kind: Service
metadata:
  name: csgames-mail-prod-backend
  labels:
    app: csgames-mail-prod
    role: master
    tier: backend
spec:
  ports:
  - port: 8090
    targetPort: 8090
  selector:
    app: csgames-mail-prod
    role: master
    tier: backend