apiVersion: v1
kind: Service
metadata:
  name: csgames-gateway-prod-backend
spec:
  selector:
    app: csgames-gateway-prod
  ports:
  - name: csgames-gateway-prod-backend
    targetPort: 8000
    port: 8000
  type: NodePort