# Declare Traefik ingress service
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-controller
spec:
  selector:
    app: traefik-ingress-controller
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-admin-ui
spec:
  selector:
    app: traefik-ingress-controller
  ports:
  - name: traefik-ui
    targetPort: 8080
    port: 8080
  type: NodePort